### GET request to example server
POST http://localhost:8080/event_maanger_war_exploded/api/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###

GET http://localhost:8080/event_maanger_war_exploded/api/admin/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6MSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzcwMjA1MjMyLCJleHAiOjE3NzAyOTE2MzJ9.8iLV_SSJI02ztoCfxyArkXXa7gFI2AW2XSC7HitfliU



